project:
  type: website

website:
  title: "ISSS608-Zhongchao"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu:
          - text: "Hand-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hand-on_Ex01.html"
          - text: "Hand-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hand-on_Ex02.html"
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 1"
            href: "In-class_Ex/In-class_ex1/In-class_ex1.html"
      - text: "Take-home Exercise"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual