project:
  type: website

website:
  title: "ISSS608-Zhongchao"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu:
          - text: "Hand-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hand-on_Ex01.html"
          - text: "Hand-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hand-on_Ex02.html"
          - text: "Hand-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hand-on_Ex03.html"
          - text: "Hand-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hand-on_Ex04.html"
          - text: "Hand-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hand-on_Ex05.html"
          - text: "Hand-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hand-on_Ex06.html"
            
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 1"
            href: "In-class_Ex/In-class_ex1/In-class_ex1.html"
            
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_ex01/Take-home_ex1.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_ex02/Take-home_ex2.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_ex03/Take-home_ex3.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual